# syntax=docker/dockerfile:1
FROM ubuntu:22.04
# install app dependencies
RUN apt-get update && apt-get install -y build-essential meson ninja-build python3-pip \
    python3-setuptools libgtk-3-dev valac vim sudo dconf-editor dbus-x11 debhelper \
    libcairo2-dev libgranite-dev libxml2-dev libgee-0.8-dev libarchive-dev libgtksourceview-4-dev \
    libmarkdown2-dev libjson-glib-dev

#libhandy-1-dev








